//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Courier.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        internal static string FeedsRequired {
            get {
                return ResourceManager.GetString("FeedsRequired", resourceCulture);
            }
        }
        
        internal static string AddCommandNameOptionRequired {
            get {
                return ResourceManager.GetString("AddCommandNameOptionRequired", resourceCulture);
            }
        }
        
        internal static string AddCommandUriOptionRequired {
            get {
                return ResourceManager.GetString("AddCommandUriOptionRequired", resourceCulture);
            }
        }
        
        internal static string AddCommandChannelOptionRequired {
            get {
                return ResourceManager.GetString("AddCommandChannelOptionRequired", resourceCulture);
            }
        }
        
        internal static string AddCommandFeedAdded {
            get {
                return ResourceManager.GetString("AddCommandFeedAdded", resourceCulture);
            }
        }
        
        internal static string ListCommandChannelOptionRequired {
            get {
                return ResourceManager.GetString("ListCommandChannelOptionRequired", resourceCulture);
            }
        }
        
        internal static string RemoveCommandChannelOptionRequired {
            get {
                return ResourceManager.GetString("RemoveCommandChannelOptionRequired", resourceCulture);
            }
        }
        
        internal static string RemoveCommandNameOptionRequired {
            get {
                return ResourceManager.GetString("RemoveCommandNameOptionRequired", resourceCulture);
            }
        }
        
        internal static string RemoveCommandNoFeedsFound {
            get {
                return ResourceManager.GetString("RemoveCommandNoFeedsFound", resourceCulture);
            }
        }
        
        internal static string RemoveCommandFeedRemoved {
            get {
                return ResourceManager.GetString("RemoveCommandFeedRemoved", resourceCulture);
            }
        }
        
        internal static string ListCommandNoFeedsFound {
            get {
                return ResourceManager.GetString("ListCommandNoFeedsFound", resourceCulture);
            }
        }
        
        internal static string AddCommandFeedAlreadyExists {
            get {
                return ResourceManager.GetString("AddCommandFeedAlreadyExists", resourceCulture);
            }
        }
    }
}
